#!#
# Copyright (c) 2026 mingcheng <mingcheng@apache.org>
#
# This source code is licensed under the MIT License,
# which is located in the LICENSE file in the source tree's root directory.
#
# File: compose.yaml
# Author: mingcheng <mingcheng@apache.org>
# File Created: 2026-01-19 12:48:00
#
# Modified By: mingcheng <mingcheng@apache.org>
# Last Modified: 2026-01-19 14:23:51
##

services:
  mihomo:
    image: docker.1ms.run/metacubex/mihomo
    container_name: mihomo
    environment:
      TZ: "Asia/Shanghai"
    dns:
      - 223.5.5.5
    volumes:
      - ./data:/etc/mihomo
    tmpfs:
      - /tmp:size=128m,mode=1777
    privileged: true
    command: ["-d", "/etc/mihomo"]
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    healthcheck:
      test: ["CMD", "nc", "-z", "172.16.1.250", "9090"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s

  zashboard:
    depends_on:
      - mihomo
    container_name: zashboard
    image: ghcr.io/zephyruso/zashboard
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      TZ: "Asia/Shanghai"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
