network:
  version: 2
  ethernets:
    mainif:
      match:
        driver: virtio_net
      set-name: eth0
      dhcp4: false
      dhcp6: false
      addresses:
        - 172.16.1.250/24
      routes:
        - to: 172.16.1.0/24
          via: 0.0.0.0
          metric: 100
          table: 100
        - to: default
          via: 172.16.1.1
          metric: 100
          table: 100
      nameservers:
        addresses:
          - 172.16.1.250
    secondary:
      match:
        driver: rndis_host
      set-name: eth1
      dhcp4: true
      dhcp4-overrides:
        use-routes: false
      dhcp6: true
      dhcp6-overrides:
        use-routes: false
      routes:
        - to: default
          via: 192.168.66.1
          metric: 101
          table: 101
