#!#
# Copyright (c) 2025 mingcheng <mingcheng@apache.org>
#
# This source code is licensed under the MIT License,
# which is located in the LICENSE file in the source tree's root directory.
#
# File: 90-multipath.yaml
# Author: mingcheng <mingcheng@apache.org>
# File Created: 2025-12-28 11:20:34
#
# Modified By: mingcheng <mingcheng@apache.org>
# Last Modified: 2025-12-29 08:20:46
##

network:
  version: 2
  ethernets:
    mainif:
      match:
        driver: virtio_net
      set-name: eth0
      dhcp4: false
      dhcp6: false
      addresses:
        - 172.16.1.250/24
      routes:
        - to: default
          via: 172.16.1.1
          metric: 100
      nameservers:
        addresses:
          - 172.16.1.1
    secondary:
      match:
        driver: rndis_host
      set-name: eth1
      dhcp4: true
      dhcp4-overrides:
        use-routes: false
      dhcp6: true
      dhcp6-overrides:
        use-routes: false
