#!#
# Copyright (c) 2025 mingcheng <mingcheng@apache.org>
#
# This source code is licensed under the MIT License,
# which is located in the LICENSE file in the source tree's root directory.
#
# File: 90-static.yaml
# Author: mingcheng (mingcheng@apache.org)
# File Created: 2025-03-20 10:36:33
#
# Modified By: mingcheng <mingcheng@apache.org>
# Last Modified: 2025-12-29 08:20:53
##

network:
  ethernets:
    mainif:
      match:
        driver: virtio_net
      # renderer: NetworkManager
      renderer: networkd
      set-name: eth0
      dhcp4: false
      dhcp6: false
      addresses:
        - 172.16.1.254/24
      routes:
        - to: default
          via: 172.16.1.1
      nameservers:
        addresses:
          - 172.16.1.1
  version: 2
