services:
  speedtest:
    container_name: speedtest
    #image: ghcr.io/librespeed/speedtest
    image: m.ixdev.cn/ghcr.io/librespeed/speedtest
    restart: always
    environment:
      MODE: standalone
      TELEMETRY: "false"
      WEBPORT: 8181
    ports:
      - 8181:8181
